import type { Metadata } from "next";
import {Outfit} from "next/font/google";
import "./globals.css";

import { ThemeProvider } from "next-themes";
import { ClerkProvider } from "@/services/clerk/ClearkProvider";

const outfitSans = Outfit({
  variable: "--font-outfit-sans",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>

      <html lang="en" suppressContentEditableWarning>
        <body
          className={`${outfitSans.variable} antialiased font-sans`}
        >
          <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableColorScheme
          disableTransitionOnChange
          >
          {children}
          </ThemeProvider>
          
        </body>
      </html>
    </ClerkProvider>
  );
}
